### ISSUE TITLE
How do you generate this cool profile

### ISSUE THREAD

**Issue by RabbitSudo** [sxlmnwb/sxlmnwb#1]
How do you generate this cool profile

**Comment by sxlmnwb** [comment]
> How do you generate this cool profile

![image](https://github-production-user-asset-6210df.s3.amazonaws.com/65052912/261073844-0ef81d5a-f2b2-4673-ab47-d755a4eb4352.png)

sorry for late reply, i'm use a picsay pro on mobile for banner design.

**Comment by nodexone** [comment]
emang boleh se cooooolll ini

**Comment by hexskrt** [comment]
hhh coolchase x

**Comment by RabbitSudo** [comment]
> > How do you generate this cool profile
> 
> ![image](https://camo.githubusercontent.com/7c2f2c74bc5a37b692f765c965648ede7829df64deb6570c0fce9a471c09ced9/68747470733a2f2f6769746875622d70726f64756374696f6e2d757365722d61737365742d3632313064662e73332e616d617a6f6e6177732e636f6d2f36353035323931322f3236313037333834342d30656638316435612d663262322d343637332d616234372d6437353561346562343335322e706e67)
> 
> sorry for late reply, i'm use a picsay pro on mobile for banner design.

x

> > How do you generate this cool profile
> 
> ![image](https://camo.githubusercontent.com/7c2f2c74bc5a37b692f765c965648ede7829df64deb6570c0fce9a471c09ced9/68747470733a2f2f6769746875622d70726f64756374696f6e2d757365722d61737365742d3632313064662e73332e616d617a6f6e6177732e636f6d2f36353035323931322f3236313037333834342d30656638316435612d663262322d343637332d616234372d6437353561346562343335322e706e67)
> 
> sorry for late reply, i'm use a picsay pro on mobile for banner design.

thank you
